name: research

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: setup tools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user --upgrade launchable~=1.0
          go get -u github.com/jstemmer/go-junit-report
          echo "LAUNCHABLE_TOKEN=${{ secrets.LAUNCHABLE_TOKEN }}" >> $GITHUB_ENV
          echo "~/.local/bin" >> $GITHUB_PATH
          env
          python3 debug.py
      - name: launchable verify
        run: |
          python3 debug.py
          ~/.local/bin/launchable verify || true
      - name: launchable record build
        run: |
          ~/.local/bin/launchable --log-level=debug record build --name $GITHUB_RUN_ID --source .
          python3 debug.py
      - name: launchable subset
        run: |
          go test -list "Test" ./... | launchable --log-level=debug subset --build $GITHUB_RUN_ID --target 70% --rest ~/launchable-rest.txt go-test > ~/launchable-subset.txt
          cat ~/launchable-subset.txt | sort
          echo "check session"
          ls -l ~/.config/launchable/sessions
          python3 debug.py
      - name: launchable record tests
        run: |
          go test -run $(cat ~/launchable-subset.txt) ./... -v 2>&1 | go-junit-report > subset.xml
          ~/.local/bin/launchable --log-level=debug record test --build $GITHUB_RUN_ID go-test ./subset.xml
          cat ./subset.xml && cat ~/launchable-subset.txt
          echo "check session"
          ls -l ~/.config/launchable/sessions
          python3 debug.py
      - name: launchable record tests rest
        run: |
          go test -run $(cat ~/launchable-rest.txt) ./... -v 2>&1 | go-junit-report > rest.xml
          ~/.local/bin/launchable --log-level=debug record test --build $GITHUB_RUN_ID go-test ./rest.xml
          cat ./rest.xml && cat ~/launchable-rest.txt
          echo "check session"
          ls -l ~/.config/launchable/sessions
          python3 debug.py
