name: Go

on:
  push:
    branches: [master]
  pull_request:

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
  LAUNCHABLE_DEBUG: 1
  GITHUB_PR_NUMBER: ${{ github.event.number }}
  # LAUNCHABLE_BASE_URL:  https://911a-14-9-37-161.ngrok.io

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools_scm
          pip install git+https://github.com/launchableinc/cli.git@tmp-github-app
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: |
          go install github.com/jstemmer/go-junit-report@latest
      - run: "launchable verify"
      - name: Record commits and build
        run: 'launchable record build --name "$GITHUB_RUN_ID"'
      - name: Subset
        run: go test -list="Test|Example" ./... | launchable subset --confidence 80%  go-test > launchable-subset.txt
      - name: Test
        run: go test $(cat launchable-subset.txt) ./... -v 2>&1 | go-junit-report -set-exit-code > report.xml
      - name: Record
        run: launchable record tests go-test report.xml
        if: always()
